name: Build v4l-utils for webOS

on:
  push:
  workflow_dispatch:

env:
  TOOLCHAIN_URL: https://github.com/openlgtv/buildroot-nc4/releases/download/webos-d7ed7ee/arm-webos-linux-gnueabi_sdk-buildroot.tar.gz
  TOOLCHAIN_SHA256: 32816626e99fb34922a49d0c639f7c8a30356fffb222372d4823027f1382f640
  TOOLCHAIN_DIR: /opt/arm-webos-linux-gnueabi_sdk-buildroot
  TOOLCHAIN_FILE: /opt/arm-webos-linux-gnueabi_sdk-buildroot/share/buildroot/toolchainfile.cmake
  INSTALL_DIR: ${{ github.workspace }}/v4l-utils-install
  KEYTABLE_DIR: ${{ github.workspace }}/v4l-utils-install/etc/rc_keymaps

jobs:
  build-v4l-utils:
    strategy:
      matrix:
        build-type: [Debug, Release]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Download and unpack toolchain
      working-directory: /opt
      run: |
        wget -q -O toolchain.tar.gz ${TOOLCHAIN_URL}
        echo "${TOOLCHAIN_SHA256} toolchain.tar.gz" | sha256sum -c -
        tar xf toolchain.tar.gz

    - name: Relocate toolchain
      working-directory: ${{ env.TOOLCHAIN_DIR }}
      run: |
        ./relocate-sdk.sh

    - name: CMake Version
      run: cmake --version

    - name: Create Build directory
      run: cmake -E make_directory ${{ github.workspace }}/build

    - name: Configure v4l-utils
      working-directory: ${{ github.workspace }}/build
      shell: bash
      run: |
        ../configure \
        --host=arm-webos-linux-gnueabi \
        --prefix=${{ env.INSTALL_DIR }} \
        --with-sysroot=${{ env.TOOLCHAIN_DIR }}/arm-webos-linux-gnueabi/sysroot \
        --keytableuserdir=${{ env.KEYTABLE_DIR }} \
        --keytablesystemdir=${{ env.KEYTABLE_DIR }}

    - name: Build v4l-utils
      working-directory: ${{ github.workspace }}/build
      run: make

    - name: Create install directories
      run: |
        mkdir -p ${{ env.INSTALL_DIR }}/bin
        mkdir -p ${{ env.KEYTABLE_DIR }}

    - name: Install v4l-utils
      working-directory: ${{ github.workspace }}/build
      run: make install

    - name: List installed files
      run: find ${{ env.INSTALL_DIR }}

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: v4l-utils_${{ matrix.build-type }}
        path: ${{ env.INSTALL_DIR }}

    - uses: DoozyX/clang-format-lint-action@v0.14
      with:
        source: './src'
        extensions: 'c,h,cpp'
        clangFormatVersion: 14

    - name: Release
      uses: softprops/action-gh-release@v1
      if: ${{ startsWith(github.ref, 'refs/tags/') && matrix.build-type == 'Release' }}
      with:
        files: |
          ${{ env.INSTALL_DIR }}/bin/*